name: Henge

on:
  push:
    branches: [ cosmosdb, main ]
  pull_request:
    branches: [ main ]

jobs:
  testWithCosmosDbSql:
    name: Test with Azure Cosmos DB (SQL API)
    runs-on: windows-2016
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Test
      run: |
        choco install azure-cosmosdb-emulator
        & "C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe"
        Start-Sleep -s 120
        try { Invoke-RestMethod -Method GET https://127.0.0.1:8081/ } catch {}
        netstat -nt
        $env:COSMOSDB_DRIVER='gocosmos'
        $env:COSMOSDB_URL='AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
        $env:TIMEZONE='Asia/Ho_Chi_Minh'
        go test -cover -coverprofile="coverage_cosmosdb_sql.txt" -v .
    - name: Codecov
      uses: codecov/codecov-action@v1.0.15
      with:
        flags: cosmosdb_sql
        name: cosmosdb_sql
