name: DynamoDB

on:
  push:
    branches: [ dynamodb, main ]
  pull_request:
    branches: [ main ]

jobs:
  testWithAwsDynamoDB:
    name: Test with AWS DynamoDB
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go env
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Start AWS DynamoDB local server
        run: docker run -d --name dynamodb -p 8000:8000 amazon/dynamodb-local -jar DynamoDBLocal.jar -inMemory -sharedDb
      - name: Test
        run: |
          export AWS_REGION="us-west-2"
          export AWS_ACCESS_KEY_ID="DUMMYIDEXAMPLE"
          export AWS_SECRET_ACCESS_KEY="DUMMYEXAMPLEKEY"
          export AWS_DYNAMODB_ENDPOINT="http://localhost:8000"
          go test -cover -coverprofile=coverage_dynamodb.txt -v .
          bash <(curl -s https://codecov.io/bash) -cF dynamodb
