name: Henge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  nojob:
    name: All jobs are running on separated action files
    runs-on: ubuntu-latest
    steps:
      - name: All jobs are running on separated action files
        run: echo "All jobs are running on separated action files"
