name: MongoDB

on:
  push:
    branches: [ mongodb, main ]
  pull_request:
    branches: [ main ]

jobs:
  testWithMongoStandalone:
    name: Test with MongoDB (Standalone)
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v5
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
    - name: Start MongoDB Standalone server
      run: docker run -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME=test -e MONGO_INITDB_ROOT_PASSWORD=test -e MONGO_INITDB_DATABASE=test -p 27017:27017 mongo:4.2
    - name: Test
      run: |
        export TIMEZONE="Asia/Ho_Chi_Minh"
        export MONGO_DB="test"
        export MONGO_URL="mongodb://test:test@localhost:27017/?authSource=admin"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_mongo_standalone.txt .
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        flags: mongo_standalone
        name: mongo_standalone

  testWithMongoReplicaSet:
    name: Test with MongoDB (ReplicaSet)
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v5
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v5
    - name: Start MongoDB ReplicaSet server
      run: docker run -d --name mongodb-replset -e MONGODB_REPLICA_SET_MODE=primary -e MONGODB_REPLICA_SET_KEY=myreplset -e MONGODB_ADVERTISED_HOSTNAME=localhost -e MONGODB_PRIMARY_PORT_NUMBER=27017 -e MONGODB_ROOT_PASSWORD=test -e MONGODB_DATABASE=test -p 27017:27017 bitnami/mongodb:4.2
    - name: Test
      run: |
        export TIMEZONE="Asia/Ho_Chi_Minh"
        export MONGO_DB="test"
        export MONGO_URL="mongodb://root:test@localhost:27017/?authSource=admin&replicaSet=replicaset"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_mongo_replicaset.txt .
    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        flags: mongo_replicaset
        name: mongo_replicaset