name: SQL

on:
  push:
    branches: [ sql, main ]
  pull_request:
    branches: [ main ]

jobs:
  testWithMySQL:
    name: Test with MySQL
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Start MySQL server
      run: docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=test -e MYSQL_DATABASE=test -e MYSQL_USER=test -e MYSQL_PASSWORD=test -p 3306:3306 mysql:8
    - name: Test
      run: |
        export TIMEZONE="Asia/Ho_Chi_Minh"
        export MYSQL_DRIVER="mysql"
        export MYSQL_URL="test:test@tcp(localhost:3306)/test?charset=utf8mb4,utf8&parseTime=false&loc=Asia%2fHo_Chi_Minh"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_mysql.txt .
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: mysql
        name: mysql

  testWithMSSQL:
    name: Test with MSSQL
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Start MSSQL server
      run: docker run -d --name mssql-express -e ACCEPT_EULA=Y -e SA_PASSWORD=SecretPassword1 -e MSSQL_PID=Express -p 1433:1433 mcr.microsoft.com/mssql/server:2019-latest
    - name: Test
      run: |
        export TIMEZONE="Asia/Ho_Chi_Minh"
        export MSSQL_DRIVER="sqlserver"
        export MSSQL_URL="sqlserver://sa:SecretPassword1@localhost:1433?database=tempdb"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_mssql.txt .
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: mssql
        name: mssql

  testWithPostgreSQL:
    name: Test with PostgreSQL
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Start PostgreSQL server
      run: docker run -d --name postgres -e POSTGRES_DB=test -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -p 5432:5432 postgres:11
    - name: Test
      run: |
        export TIMEZONE="Asia/Ho_Chi_Minh"
        export PGSQL_DRIVER="pgx"
        export PGSQL_URL="postgres://test:test@localhost:5432/test?sslmode=disable&client_encoding=UTF-8&application_name=henge"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_pgsql.txt .
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: pgsql
        name: pgsql

  testWithSqlite:
    name: Test with SQLite
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Test
      run: |
        export TIMEZONE="Asia/Ho_Chi_Minh"
        mkdir ./temp
        export SQLITE_DRIVER="sqlite3"
        export SQLITE_URL="./temp/temp.db"
        go test -v -count 1 -p 1 -cover -coverprofile=coverage_sqlite.txt .
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: sqlite
        name: sqlite

  testWithCosmosDbSql:
    name: Test with Azure Cosmos DB (SQL API)
    runs-on: windows-latest
    steps:
    - name: Set up Go env
      uses: actions/setup-go@v4
      with:
        go-version: ^1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Test
      run: |
        choco install azure-cosmosdb-emulator
        & "C:\Program Files\Azure Cosmos DB Emulator\Microsoft.Azure.Cosmos.Emulator.exe"
        Start-Sleep -s 120
        try { Invoke-RestMethod -Method GET https://127.0.0.1:8081/ } catch {}
        netstat -nt
        $env:COSMOSDB_DRIVER='gocosmos'
        $env:COSMOSDB_URL='AccountEndpoint=https://127.0.0.1:8081/;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=='
        $env:TIMEZONE='Asia/Ho_Chi_Minh'
        go test -v -count 1 -p 1 -cover -coverprofile="coverage_cosmosdb_sql.txt" .
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: cosmosdb_sql
        name: cosmosdb_sql
